on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1

  publish:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        package:
          - core-api
          - addon-api
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: ${{ matrix.package }}
          against: https://github.com/unifi-blueberry/api.git#branch=main,ref=HEAD~1,subdir=${{ matrix.package }}
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: ${{ matrix.package }}
          draft: ${{ github.ref_name != 'main'}}
